package api.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import api.dao.WeatherIcon;
import api.dao.City;

import api.dao.WeatherIconDao;
import api.dao.CityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weatherIconDaoConfig;
    private final DaoConfig cityDaoConfig;

    private final WeatherIconDao weatherIconDao;
    private final CityDao cityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weatherIconDaoConfig = daoConfigMap.get(WeatherIconDao.class).clone();
        weatherIconDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        weatherIconDao = new WeatherIconDao(weatherIconDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);

        registerDao(WeatherIcon.class, weatherIconDao);
        registerDao(City.class, cityDao);
    }
    
    public void clear() {
        weatherIconDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
    }

    public WeatherIconDao getWeatherIconDao() {
        return weatherIconDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

}
