package api.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TB_weather_icon".
 */
public class WeatherIcon {

    /** Not-null value. */
    private String code;
    /** Not-null value. */
    private String txt;
    /** Not-null value. */
    private String txt_en;
    /** Not-null value. */
    private String icon;

    public WeatherIcon() {
    }

    public WeatherIcon(String code, String txt, String txt_en, String icon) {
        this.code = code;
        this.txt = txt;
        this.txt_en = txt_en;
        this.icon = icon;
    }

    /** Not-null value. */
    public String getCode() {
        return code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCode(String code) {
        this.code = code;
    }

    /** Not-null value. */
    public String getTxt() {
        return txt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTxt(String txt) {
        this.txt = txt;
    }

    /** Not-null value. */
    public String getTxt_en() {
        return txt_en;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTxt_en(String txt_en) {
        this.txt_en = txt_en;
    }

    /** Not-null value. */
    public String getIcon() {
        return icon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIcon(String icon) {
        this.icon = icon;
    }

}
